### ISSUE TITLE
Logo Definition

### ISSUE THREAD

**Issue by valentinotheworld** [Bad-Developers-Troop/polarisdesk#1]
Definire il logo per PolarDesk.
Must: stile retrowave

**Comment by valentinotheworld** [comment]
![PolarisDeskLogo](https://user-images.githubusercontent.com/70565740/100745512-ae4df400-33df-11eb-9d97-5bed0466a718.png)

Logo created

**Comment by kasuken** [comment]
@valentinotheworld can you make a version with no background colour? just the logo?
